// generated by build_frequency_lists.py
#ifndef __ZXCVBN___FREQUENCY_LISTS_HPP
#define __ZXCVBN___FREQUENCY_LISTS_HPP

#include <zxcvbn/frequency_lists_common.hpp>

#include <initializer_list>
#include <unordered_map>

namespace zxcvbn {

namespace _frequency_lists {

enum class DictionaryTag {
  ENGLISH_WIKIPEDIA,
  FEMALE_NAMES,
  MALE_NAMES,
  PASSWORDS,
  SURNAMES,
  US_TV_AND_FILM,
  USER_INPUTS
};

std::unordered_map<DictionaryTag, RankedDict> & get_default_ranked_dicts();

}

}

#endif